# Generated by Django 5.0.4 on 2025-02-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age_group', models.CharField(choices=[('Elderly', 'Elderly'), ('Middle Aged', 'Middle Age'), ('Young Adult', 'Young Adult')], max_length=20)),
                ('campaign_contacts', models.IntegerField()),
                ('contact_duration', models.IntegerField()),
                ('contact_type', models.CharField(choices=[('cellular', 'cellular'), ('unknown', 'unknown'), ('telephone', 'telephone')], max_length=20)),
                ('days_last_contacted', models.IntegerField()),
                ('personal_loan', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=20)),
                ('poutcome', models.CharField(choices=[('success', 'succes'), ('unknown', 'unknown'), ('failure', 'failure'), ('other', 'other')], max_length=20)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
