# Generated by Django 5.0.4 on 2025-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='classification',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
